initial project
Brightcoders-Bootcamps/kata-05-reservacion-vuelo-kata-05-team-02 pull request #5
Opened 2020-10-20 18:25 UTC by JordiGN

# Description
What did you implemented/Why did you implemented this:
 - Initial setup.
- Create a React-Native application. 
- Correct execution
- This commit is related to issue #2 
 

 # Testing
Download code, enter to project folder run _npm install_ on the console, run _npx react-native start_ and in another console run _npx react-native run-android_

for iOS run _npx pod-install_ and then _npx react-native run-ios_

2020-10-20 19:24 UTC, OwenRamire requested changes
When you create your setup, just delete all the things that you think you won't use or just delete the code lines on `App.js` and do:
- `git add .`
- `git commit -m "React Native init"` or `Initial commit` 
on your master branch.

2020-10-20 19:24 UTC, OwenRamire commented on FlightReservation/App.js
> +import React from 'react';
Delete all the code lines or you could leave something like this:
```javascript
import React from 'react';
import {SafeAreaView, Text, StyleSheet} from 'react-native';

const App = () => {
   return (
   <SafeAreaView style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>Hello world</Text>
   </SafeAreaView>
   );
}

export default App;
```

2020-10-20 19:35 UTC, OwenRamire approved these changes

2020-10-21 15:31 UTC, 1ng-HeberH approved these changes

2020-10-21 15:31 UTC, alcamk approved these changes
It's ok for me

2020-10-21 15:32 UTC, alcamk approved these changes
It's ok

2020-10-21 15:33 UTC, merged